"use client"

import localFont from "next/font/local";
import { SessionProvider } from "next-auth/react";
import "./globals.css";
import Nav from "@/components/navigation/nav";
import Footer from "@/components/footer/Footer";
import { Elements } from "@stripe/react-stripe-js";
import { loadStripe } from '@stripe/stripe-js';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

 /* export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

const stripePromise = loadStripe('pk_test_51QUzDIDZC923TJqPUleeo9KV41EkA6oIUXwcj42SQ4y5WvrulvUcYW6cNtmalsOtlOHsju8l65chHq23kBID80SD00HtpeKCyN');

export default function RootLayout({ children }) {
  return (
    <Elements stripe={stripePromise}>
    <SessionProvider>
      <html lang="es">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Nav />
          {children}
          <Footer />
        </body>
      </html>
    </SessionProvider>
    </Elements>
  );
}
